# example of hyperparameters.yaml
random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

gradient_boosting:
  learning_rate: 0.1
  n_estimators: 100
  max_depth: 3
  min_samples_split: 2
  min_samples_leaf: 1

svm:
  C: 1.0
  kernel: 'rbf'
  gamma: 'scale'

neural_network:
  learning_rate: 0.001
  epochs: 50
  batch_size: 32
  layers:
    - units: 64
      activation: 'relu'
    - units: 32
      activation: 'relu'
    - units: 1
      activation: 'sigmoid'
