name: 'Cookiecutter Action'
description: 'Generates a project structure from a Cookiecutter template using dynamic inputs'
inputs:
  template_json_variables:
    description: 'JSON string containing all the template variables'
    required: true
  template_repo_url:
    description: 'Cookiecutter template git repository URL'
    required: true
  template_directory:
    description: 'Relative path within the repository to the template directory'
    required: true
  output_directory:
    description: 'Output directory for the generated project'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: python3 -m pip install cookiecutter
      shell: bash

    - name: Create temp directory
      run: mkdir temp_action_dir
      shell: bash      

    - name: Download Python Script
      working-directory: temp_action_dir
      run: wget https://raw.githubusercontent.com/jimmfan/cookiecutter-action/main/generate_template.py
      shell: bash

    - name: Set TEMPLATE_VARIABLES_JSON
      run: |
        content=$(jq -c @json ${{ inputs.template_json_variables }})
        echo "TEMPLATE_JSON_VARIABLES=$content" >> $GITHUB_ENV
      shell: bash

    - name: Generate Project with Cookiecutter
      working-directory: temp_action_dir
      run: python3 generate_template.py
      shell: bash
      env:
        TEMPLATE_JSON_VARIABLES: ${{ env.TEMPLATE_JSON_VARIABLES }}
        TEMPLATE_REPO_URL: ${{ inputs.template_repo_url }}
        TEMPLATE_DIRECTORY: ${{ inputs.template_directory || '.' }}
        OUTPUT_DIRECTORY: ${{ inputs.output_directory || '.' }}

    - name: Unpack to root directory and cleanup files
      run: |
        rm -rf .github/
        PROJECT_NAME=$(echo '${{ inputs.template_json_variables }}' | jq -r '.project_name')
        shopt -s dotglob
        mv temp_action_dir/$PROJECT_NAME/* .
        shopt -u dotglob
        rm -rf temp_action_dir
      shell: bash