name: 'Cookiecutter Action'
description: 'Generates a project structure from a Cookiecutter template using dynamic inputs'
inputs:
  template_repo_url:
    description: 'Cookiecutter template git repository URL'
    required: true
  template_variables_json:
    description: 'JSON string containing all the template variables'
    required: true
  template_directory:
    description: 'Relative path within the repository to the template directory'
    required: false
  output_directory:
    description: 'Output directory for the generated project'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      run: python3 -m pip install cookiecutter
      shell: bash

    - name: Generate Project with Cookiecutter
      run: python3 -m ./generate_template.py
      shell: bash
      env:
        TEMPLATE_REPO_URL: ${{ inputs.template_repo_url }}
        TEMPLATE_VARIABLES_JSON: ${{ inputs.template_variables_json }}
        TEMPLATE_DIRECTORY: ${{ inputs.template_directory || '.' }}
        OUTPUT_DIRECTORY: ${{ inputs.output_directory || '.' }}