repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # use the version you're targeting
    hooks:
      - id: ruff
        args: ["check", "src", "tests"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
